{% set name = "sspace_basic" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nsoranzo/{{name}}/archive/v{{version}}.tar.gz
  md5: 826684a3da48282a6fb7943e1523931

build:
  number: 0
  skip: True  
  run_exports: 
  - {{pin_subpackage("sspace_basic", max_pin="x")}}

requirements:
  run:
    - python
    - perl >= 5.24
    - bowtie >=1.1.2

test:
  commands:
    - SSPACE_Basic.pl -help 2>&1 | grep 'Usage'

about:
  home: https://github.com/nsoranzo/sspace_basic
  license: GNU General Public License v2
  summary: Scaffolding Pre-Assemblies After Contig Extension (SSPACE)
  dev_url: https://github.com/nsoranzo/sspace_basic
  doc_url: https://github.com/nsoranzo/sspace_basic


extra:
  additional-platforms:
    - linux-aarch64